swagger: '2.0'
info:
 
paths:
  /home:
    get:
      produces:
      - application/json
      parameters:
      responses:
        200:
          description: successful operation
        400:
          description: Invalid status value
  /values:
    get:
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        required: true
      - name: count
        in: path
        required: true
      responses:
        200:
          description: successful operation
        400:
          description: Invalid status value
  /items:
    get:
      produces:
      - application/json
      parameters:
      - name: name
        in: query
        required: true
      - name: count
        in: query
        required: true
      responses:
        200:
          description: successful operation
        400:
          description: Invalid status value
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /sela-egged/Pets/1.0.0
schemes:
- https
- http